# ────────────────────────────────────────────────────────────────────────────────
# dbt_project.yml
#
# Project:        data_management_2_arun
# Purpose:        Defines how dbt builds models into BigQuery,
#                 partitioned into raw, staging, and analytics layers.
# Created:        2025-05-02
# ────────────────────────────────────────────────────────────────────────────────

# 1) Project identity — must be lowercase, underscore
name: 'data_management_2_arun'
version: '1.0.0'
config-version: 2

# 2) Profile — references your ~/.dbt/profiles.yml for BigQuery credentials
profile: 'default'

# 3) File locations — you generally won’t change these
model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

# 4) Target directories for compiled artifacts
target-path: "target"       # compiled SQL, manifest.json, etc.
clean-targets:             # directories removed by `dbt clean`
  - "target"
  - "dbt_packages"

# ────────────────────────────────────────────────────────────────────────────────
# 5) Model configurations by folder
#
# We use three BigQuery datasets to isolate each layer:
#   • raw       ← source tables (loaded externally)
#   • stg       ← staging views
#   • analytics ← dimension & fact tables
# ────────────────────────────────────────────────────────────────────────────────

models:
  # Top‐level key must match the project name above
  data_management_2_arun:
    
    # ──────────────── Raw sources ────────────────
    # These are your landing tables (raw JSON payloads). We never materialize SQL here.
    src:
      +materialized: ephemeral
      +schema: data_management_2_arun

    # ────────────── Staging layer ───────────────
    # Flattened, cleaned staging views that feed your dims & facts.
    staging:
      +materialized: view
      +schema: stg

    # ──────────── Dimension tables ───────────────
    # Persisted tables for your dimensional lookups (e.g. stations, date).
    dimensions:
      +materialized: table
      +schema: analytics

    # ────────────── Fact tables ──────────────────
    # Persisted tables for your business metrics (status history, trips).
    facts:
      +materialized: table
      +schema: analytics

    # ─────────── Default for any other models ───────
    # If you create models outside src/staging/dimensions/facts,
    # they will be built as views in the default analytics schema.
    +materialized: view

# ────────────────────────────────────────────────────────────────────────────────
# Notes:
# • Make sure the three datasets exist in BigQuery:
#     raw
#     stg
#     analytics
#
# • Your BigQuery profile (in ~/.dbt/profiles.yml) should point at the
#   project 'data-management-2-arun' and can use any default dataset;
#   overrides above will direct specific models into the correct datasets.
#
# • Run your pipeline:
#     dbt run
#     dbt test
#     dbt docs generate
# ────────────────────────────────────────────────────────────────────────────────
